apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-web-app-build
  namespace: tekton-runs
spec:
  description: >-
    The pipeline will build the node-web-app and loadgenerator containers and publish them to the local container registry
  params:
    - name: repo
      description: The git repo
      default: https://gitlab.com/deimosdev/tooling/myapp.git
    - name: revision
      description: The git revision to use
      default: main
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
        - name: depth
          value: "0"
      workspaces:
        - name: output
          workspace: source
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: 'true'
  generateName: test-node-web-app-build-
  labels:
    app.kubernetes.io/instance: gitops-tekton-annotations
  name: test-node-web-app-build
  namespace: tekton-runs
spec:
  pipelineRef:
    name: node-web-app-build
  serviceAccountName: gitlab-deimosdev
  timeout: 1h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi