# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# commonAnnotations:
#   deimos.io/application: sips-cicd
#   deimos.io/customer: deimos.io
#   deimos.io/owner: sre@deimos.io
#   deimos.io/project: sips-cicd
#   deimos.io/version: 0.0.1

#   deimos.io/repo: https://github.com/DeimosCloud/sips-cicd.git

# resources: 
#   - deimos.io
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  deimos.io/application: myapp
  deimos.io/customer: deimos.io
  deimos.io/owner: sre@deimos.io
  deimos.io/project: myapp
  deimos.io/version: 0.0.1
  deimos.io/repo: https://github.com/deimoscloud/myapp.git
resources: 
  - deimos.io
  - loadgenerator.yaml
  - node-web-app.yaml
  - rabbitmq-cluster-operator.yaml
  - tekton.yaml